#Configuration for failfast=false

# HTTP Server
server:
  port: ${PORT:2222}   # HTTP port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/