# HTTP Server
server:
  #port: ${PORT:3334}   # HTTP port
  port: ${PORT:random.int[3331,3999]}   # HTTP port

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
