# HTTP Server
server:
  port: ${PORT:random.long[3331,3999]}   # HTTP port

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
